export const mockBranches = [
  {
    id: 'mock-1',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-1',
    title: 'Brain Academy Bandung',
    brandId: 'brainacademy',
    brandConfidence: 'high',
    storeCode: 'BA-BDG',
    address: 'Bandung',
    profileStatus: 'verified',
    verified: true,
    averageRating: 4.3,
    totalReviews: 42,
    completionStatus: 'not-complete',
    blockingReason: 'rating',
    websiteClicks: { current: 120, previous: 100, deltaPercent: 20 },
    callClicks: { current: 31, previous: 35, deltaPercent: -11.43 },
    directionRequests: { current: 44, previous: 40, deltaPercent: 10 },
    lastSyncedAt: '2026-05-25T02:00:00.000Z'
  },
  {
    id: 'mock-2',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-2',
    title: 'English Academy Bekasi',
    brandId: 'englishacademy',
    brandConfidence: 'high',
    storeCode: 'EA-BKS',
    address: 'Bekasi',
    profileStatus: 'verified',
    verified: true,
    averageRating: 4.8,
    totalReviews: 7,
    completionStatus: 'not-complete',
    blockingReason: 'reviews',
    websiteClicks: { current: 84, previous: 80, deltaPercent: 5 },
    callClicks: { current: 22, previous: 20, deltaPercent: 10 },
    directionRequests: { current: 18, previous: 16, deltaPercent: 12.5 },
    lastSyncedAt: '2026-05-25T02:00:00.000Z'
  },
  {
    id: 'mock-3',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-3',
    title: 'Ruangguru Privat Depok',
    brandId: 'ruangguru-privat',
    brandConfidence: 'high',
    storeCode: null,
    address: 'Depok',
    profileStatus: 'unverified',
    verified: false,
    averageRating: null,
    totalReviews: null,
    completionStatus: 'not-complete',
    blockingReason: 'not-registered',
    websiteClicks: { current: 0, previous: 0, deltaPercent: null },
    callClicks: { current: 0, previous: 0, deltaPercent: null },
    directionRequests: { current: 0, previous: 0, deltaPercent: null },
    lastSyncedAt: '2026-05-25T02:00:00.000Z'
  },
  {
    id: 'mock-4',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-4',
    title: 'Cabang Pak Budi Depok',
    brandId: 'needs-review',
    brandConfidence: 'low',
    storeCode: null,
    address: 'Depok',
    profileStatus: 'missing-store-code',
    verified: false,
    averageRating: null,
    totalReviews: null,
    completionStatus: 'not-complete',
    blockingReason: 'needs-review',
    websiteClicks: { current: null, previous: null, deltaPercent: null },
    callClicks: { current: null, previous: null, deltaPercent: null },
    directionRequests: { current: null, previous: null, deltaPercent: null },
    lastSyncedAt: '2026-05-25T02:00:00.000Z'
  }
];
