export const mockBranches = [
  {
    id: 'mock-1',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-1',
    title: 'Brain Academy Bandung',
    brandId: 'brainacademy',
    brandConfidence: 'high',
    storeCode: 'BA-BDG',
    address: 'Bandung',
    profileStatus: 'verified',
    verified: true,
    averageRating: 4.3,
    totalReviews: 42,
    completionStatus: 'not-complete',
    blockingReason: 'rating',
    websiteClicks: { current: 120, previous: 100, deltaPercent: 20 },
    callClicks: { current: 31, previous: 35, deltaPercent: -11.43 },
    directionRequests: { current: 44, previous: 40, deltaPercent: 10 },
    lastSyncedAt: '2026-05-25T02:00:00.000Z'
  },
  {
    id: 'mock-2',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-2',
    title: 'English Academy Bekasi',
    brandId: 'englishacademy',
    brandConfidence: 'high',
    storeCode: 'EA-BKS',
    address: 'Bekasi',
    profileStatus: 'verified',
    verified: true,
    averageRating: 4.8,
    totalReviews: 7,
    completionStatus: 'not-complete',
    blockingReason: 'reviews',
    websiteClicks: { current: 84, previous: 80, deltaPercent: 5 },
    callClicks: { current: 22, previous: 20, deltaPercent: 10 },
    directionRequests: { current: 18, previous: 16, deltaPercent: 12.5 },
    lastSyncedAt: '2026-05-25T02:00:00.000Z'
  },
  {
    id: 'mock-3',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-3',
    title: 'Ruangguru Privat Depok',
    brandId: 'ruangguru-privat',
    brandConfidence: 'high',
    storeCode: null,
    address: 'Depok',
    profileStatus: 'unverified',
    verified: false,
    averageRating: null,
    totalReviews: null,
    completionStatus: 'not-complete',
    blockingReason: 'not-registered',
    websiteClicks: { current: 0, previous: 0, deltaPercent: null },
    callClicks: { current: 0, previous: 0, deltaPercent: null },
    directionRequests: { current: 0, previous: 0, deltaPercent: null },
    lastSyncedAt: '2026-05-25T02:00:00.000Z'
  },
  {
    id: 'mock-4',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-4',
    title: 'Cabang Pak Budi Depok',
    brandId: 'needs-review',
    brandConfidence: 'low',
    storeCode: null,
    address: 'Depok',
    profileStatus: 'missing-store-code',
    verified: false,
    averageRating: null,
    totalReviews: null,
    completionStatus: 'not-complete',
    blockingReason: 'needs-review',
    websiteClicks: { current: null, previous: null, deltaPercent: null },
    callClicks: { current: null, previous: null, deltaPercent: null },
    directionRequests: { current: null, previous: null, deltaPercent: null },
    lastSyncedAt: '2026-05-25T02:00:00.000Z'
  },
  {
    id: 'mock-5',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-5',
    title: 'MatChamps Surabaya Manyar',
    brandId: 'mathchamps',
    brandConfidence: 'high',
    storeCode: 'MC-SBY-MYR',
    address: 'Surabaya',
    profileStatus: 'verified',
    verified: true,
    averageRating: 4.6,
    totalReviews: 18,
    completionStatus: 'complete',
    blockingReason: 'complete',
    websiteClicks: { current: 142, previous: 118, deltaPercent: 20.34 },
    callClicks: { current: 28, previous: 22, deltaPercent: 27.27 },
    directionRequests: { current: 57, previous: 51, deltaPercent: 11.76 },
    lastSyncedAt: '2026-06-27T04:00:00.000Z'
  },
  {
    id: 'mock-6',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-6',
    title: 'Alta Global School Jakarta Selatan',
    brandId: 'altaglobal-school',
    brandConfidence: 'high',
    storeCode: 'AGS-JKS',
    address: 'Jakarta Selatan',
    profileStatus: 'google-update',
    verified: true,
    averageRating: 4.7,
    totalReviews: 33,
    completionStatus: 'complete',
    blockingReason: 'complete',
    websiteClicks: { current: 96, previous: 104, deltaPercent: -7.69 },
    callClicks: { current: 16, previous: 18, deltaPercent: -11.11 },
    directionRequests: { current: 39, previous: 45, deltaPercent: -13.33 },
    lastSyncedAt: '2026-06-27T04:00:00.000Z'
  },
  {
    id: 'mock-7',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-7',
    title: 'Wonderlab Tangerang BSD',
    brandId: 'wonderlab',
    brandConfidence: 'high',
    storeCode: 'WL-BSD',
    address: 'Tangerang Selatan',
    profileStatus: 'verified',
    verified: true,
    averageRating: 4.9,
    totalReviews: 27,
    completionStatus: 'complete',
    blockingReason: 'complete',
    websiteClicks: { current: 121, previous: 88, deltaPercent: 37.5 },
    callClicks: { current: 24, previous: 19, deltaPercent: 26.32 },
    directionRequests: { current: 46, previous: 30, deltaPercent: 53.33 },
    lastSyncedAt: '2026-06-27T04:00:00.000Z'
  },
  {
    id: 'mock-8',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-8',
    title: 'Brain Academy Yogyakarta Seturan',
    brandId: 'brainacademy',
    brandConfidence: 'high',
    storeCode: 'BA-YK-STN',
    address: 'Yogyakarta',
    profileStatus: 'suspended',
    verified: false,
    averageRating: 4.2,
    totalReviews: 12,
    completionStatus: 'not-complete',
    blockingReason: 'not-registered',
    websiteClicks: { current: 12, previous: 76, deltaPercent: -84.21 },
    callClicks: { current: 3, previous: 18, deltaPercent: -83.33 },
    directionRequests: { current: 2, previous: 31, deltaPercent: -93.55 },
    lastSyncedAt: '2026-06-27T04:00:00.000Z'
  },
  {
    id: 'mock-9',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-9',
    title: 'English Academy Medan',
    brandId: 'englishacademy',
    brandConfidence: 'high',
    storeCode: 'EA-MDN',
    address: 'Medan',
    profileStatus: 'verified',
    verified: true,
    averageRating: 4.4,
    totalReviews: 44,
    completionStatus: 'not-complete',
    blockingReason: 'rating',
    websiteClicks: { current: 78, previous: 91, deltaPercent: -14.29 },
    callClicks: { current: 11, previous: 17, deltaPercent: -35.29 },
    directionRequests: { current: 25, previous: 29, deltaPercent: -13.79 },
    lastSyncedAt: '2026-06-27T04:00:00.000Z'
  },
  {
    id: 'mock-10',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-10',
    title: 'Ruangguru Privat Semarang',
    brandId: 'ruangguru-privat',
    brandConfidence: 'high',
    storeCode: 'RGP-SMG',
    address: 'Semarang',
    profileStatus: 'pending-review',
    verified: false,
    averageRating: 4.8,
    totalReviews: 9,
    completionStatus: 'not-complete',
    blockingReason: 'reviews',
    websiteClicks: { current: 41, previous: 36, deltaPercent: 13.89 },
    callClicks: { current: 8, previous: 6, deltaPercent: 33.33 },
    directionRequests: { current: 15, previous: 14, deltaPercent: 7.14 },
    lastSyncedAt: '2026-06-27T04:00:00.000Z'
  },
  {
    id: 'mock-11',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-11',
    title: 'Brain Academy Makassar Panakkukang',
    brandId: 'brainacademy',
    brandConfidence: 'high',
    storeCode: 'BA-MKS-PNK',
    address: 'Makassar',
    profileStatus: 'verified',
    verified: true,
    averageRating: 4.8,
    totalReviews: 51,
    completionStatus: 'complete',
    blockingReason: 'complete',
    websiteClicks: { current: 156, previous: 140, deltaPercent: 11.43 },
    callClicks: { current: 36, previous: 30, deltaPercent: 20 },
    directionRequests: { current: 64, previous: 59, deltaPercent: 8.47 },
    lastSyncedAt: '2026-06-27T04:00:00.000Z'
  },
  {
    id: 'mock-12',
    accountName: 'accounts/mock',
    locationName: 'locations/mock-12',
    title: 'Wonderlab Bandung Dago',
    brandId: 'wonderlab',
    brandConfidence: 'high',
    storeCode: null,
    address: 'Bandung',
    profileStatus: 'missing-store-code',
    verified: true,
    averageRating: 4.6,
    totalReviews: 16,
    completionStatus: 'not-complete',
    blockingReason: 'needs-review',
    websiteClicks: { current: 63, previous: 58, deltaPercent: 8.62 },
    callClicks: { current: 14, previous: 12, deltaPercent: 16.67 },
    directionRequests: { current: 21, previous: 24, deltaPercent: -12.5 },
    lastSyncedAt: '2026-06-27T04:00:00.000Z'
  }
];
